---
services:
  app:
    build:
      context: ./
      dockerfile: dev/docker/services/app/Dockerfile
      args:
        - "PHP_IMAGE_APP_VERSION=8.4.4-fpm-alpine3.20"
        - "COMPOSER_AUTH=${COMPOSER_AUTH?err}"
    volumes:
      - ./:/shrikeh
