---
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Shrikeh\SymfonyApp\:
    resource: '../src/'
    exclude:
      - '../src/Uid/Id'
    
  Shrikeh\SymfonyApp\Bus\SymfonyCommandBus: ~
  Shrikeh\SymfonyApp\Bus\SymfonyQueryBus: ~

  Shrikeh\SymfonyApp\Logger\Psr3AppLogger: ~
  Shrikeh\SymfonyApp\Log: '@Shrikeh\App\Logger\Psr3AppLogger'

  Shrikeh\SymfonyApp\Command\CommandBus: '@Shrikeh\App\Bus\SymfonyCommandBus'
  Shrikeh\SymfonyApp\Command\QueryBus: '@Shrikeh\App\Bus\SymfonyQueryBus'

  _instanceof:
    Shrikeh\SymfonyApp\Query\QueryHandler:
      tags:
        - { name: messenger.message_handler, bus: 'query.bus' }
    Shrikeh\SymfonyApp\Command\CommandHandler:
      tags:
        - { name: messenger.message_handler, bus: 'command.bus' }
